
FLAGS = -bin-annot -g -annot
JSPKGS = -package js_of_ocaml -package js_of_ocaml.syntax \
	 -syntax camlp4o -linkpkg

REPKG= -package re

CAMLC = ocamlc
CAMLLEX = ocamllex
CAMLDEP = ocamldep
CAMLFIND = ocamlfind
CAMLJS = $(CAMLFIND) $(CAMLC) $(JSPKGS) $(FLAGS) 

PP = "camlp4o ~/.opam/4.00.1/lib/js_of_ocaml/pa_js.cmo"
